version: 0.2
phases:
  pre_build:
    commands:
      - $(aws ecr get-login --no-include-email)
      - TAG="$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | head -c 8)"
      - IMAGE_URI="${REPOSITORY_URI}:${TAG}"
  build:
    commands:
      - ls
      - docker build --tag "$IMAGE_URI" ./ecs-demo-php-simple-app
  post_build:
    commands:
      - docker push "$IMAGE_URI"
      - printf '[{"name":"simple-app","imageUri":"%s"}]' "$IMAGE_URI" > images.json
artifacts:
  type: zip
  files:
    - images.json
    - infrastructure/**/*
  discard-paths: yes